-- Create the reports table
-- Used to store conversation summaries and titles generated by LLM
CREATE TABLE reports (
    id VARCHAR(36) PRIMARY KEY,                    -- UUID generated by uuid.uuid4()
    session_id VARCHAR(255) NOT NULL,              -- Session identifier
    content JSON NOT NULL,                         -- JSON content with title and summary
    createdAt DATETIME NOT NULL,                   -- Creation timestamp in UTC
    INDEX idx_session_id (session_id),             -- Index for session lookups
    INDEX idx_created_at (createdAt)               -- Index for time-based queries
);

-- Create the dementia_analysis table  
-- Used to store dementia risk analysis results from Vertex AI endpoint
CREATE TABLE dementia_analysis (
    id VARCHAR(36) PRIMARY KEY,                    -- UUID generated by uuid.uuid4()
    session_id VARCHAR(255) NOT NULL,              -- Session identifier
    user_id VARCHAR(255) NOT NULL,                 -- User identifier
    risk_score DECIMAL(5,4) NOT NULL,              -- Risk score (0.0000 to 1.0000)
    createdAt DATETIME NOT NULL,                   -- Creation timestamp in UTC
    INDEX idx_session_id (session_id),             -- Index for session lookups
    INDEX idx_user_id (user_id),                   -- Index for user lookups
    INDEX idx_created_at (createdAt),              -- Index for time-based queries
    INDEX idx_risk_score (risk_score),             -- Index for risk score analysis
    CONSTRAINT chk_risk_score CHECK (risk_score >= 0.0 AND risk_score <= 1.0)
);

-- Create the emotion_analysis table
-- Used to store emotion analysis results from Hugging Face Zero-Shot model
CREATE TABLE emotion_analysis (
    id VARCHAR(36) PRIMARY KEY,                    -- UUID generated by uuid.uuid4()
    session_id VARCHAR(255) NOT NULL,              -- Session identifier
    user_id VARCHAR(255) NOT NULL,                 -- User identifier
    happy DECIMAL(5,4) NOT NULL DEFAULT 0.0,      -- Happy emotion score (0.0000 to 1.0000)
    sad DECIMAL(5,4) NOT NULL DEFAULT 0.0,        -- Sad emotion score (0.0000 to 1.0000)
    angry DECIMAL(5,4) NOT NULL DEFAULT 0.0,      -- Angry emotion score (0.0000 to 1.0000)
    surprised DECIMAL(5,4) NOT NULL DEFAULT 0.0,  -- Surprised emotion score (0.0000 to 1.0000)
    bored DECIMAL(5,4) NOT NULL DEFAULT 0.0,      -- Bored emotion score (0.0000 to 1.0000)
    createdAt DATETIME NOT NULL,                   -- Creation timestamp in UTC
    INDEX idx_session_id (session_id),             -- Index for session lookups
    INDEX idx_user_id (user_id),                   -- Index for user lookups  
    INDEX idx_created_at (createdAt),              -- Index for time-based queries
    CONSTRAINT chk_happy CHECK (happy >= 0.0 AND happy <= 1.0),
    CONSTRAINT chk_sad CHECK (sad >= 0.0 AND sad <= 1.0),
    CONSTRAINT chk_angry CHECK (angry >= 0.0 AND angry <= 1.0),
    CONSTRAINT chk_surprised CHECK (surprised >= 0.0 AND surprised <= 1.0),
    CONSTRAINT chk_bored CHECK (bored >= 0.0 AND bored <= 1.0)
);